/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => XHSBatchImporterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  defaultFolder: "XHS Notes",
  categories: ["AI", "\u7F8E\u672F", "\u65C5\u884C", "\u7F8E\u98DF", "\u77E5\u8BC6", "\u5A31\u4E50"],
  downloadMedia: false,
  autoScrollDelay: 1500,
  requestDelay: 1e3,
  opencliPath: "/Users/yangfan/.npm-global/bin/opencli",
  userId: "",
  importMode: "incremental"
};

// src/settings.ts
var import_obsidian = require("obsidian");
var XHSBatchImporterSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "XHS Batch Importer Settings" });
    new import_obsidian.Setting(containerEl).setName("Import mode").setDesc("Full: scan all favorites. Incremental: only new favorites since last run (stops scrolling when previously seen notes are found).").addDropdown(
      (dropdown) => dropdown.addOption("full", "Full - Read all favorites").addOption("incremental", "Incremental - Only new since last run").setValue(this.plugin.settings.importMode).onChange(async (value) => {
        this.plugin.settings.importMode = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default folder").setDesc("Folder to store imported notes (relative to vault root)").addText(
      (text) => text.setPlaceholder("XHS Notes").setValue(this.plugin.settings.defaultFolder).onChange(async (value) => {
        this.plugin.settings.defaultFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Categories").setDesc("Comma-separated list of categories for organizing notes").addText(
      (text) => text.setPlaceholder("AI, \u7F8E\u672F, \u65C5\u884C").setValue(this.plugin.settings.categories.join(", ")).onChange(async (value) => {
        this.plugin.settings.categories = value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("XHS User ID").setDesc("Your Xiaohongshu user ID (auto-detected if empty)").addText(
      (text) => text.setPlaceholder("e.g., 6904ff29000000003702d2b6").setValue(this.plugin.settings.userId).onChange(async (value) => {
        this.plugin.settings.userId = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Download media").setDesc("Download images/videos (default: off to save disk space)").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.downloadMedia).onChange(async (value) => {
        this.plugin.settings.downloadMedia = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto scroll delay (ms)").setDesc("Delay between scroll actions when loading favorites (ms)").addSlider(
      (slider) => slider.setLimits(500, 5e3, 100).setValue(this.plugin.settings.autoScrollDelay).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.autoScrollDelay = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Request delay (ms)").setDesc("Delay between importing each note (ms)").addSlider(
      (slider) => slider.setLimits(200, 5e3, 100).setValue(this.plugin.settings.requestDelay).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.requestDelay = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("opencli path").setDesc("Path to opencli binary").addText(
      (text) => text.setPlaceholder("opencli").setValue(this.plugin.settings.opencliPath).onChange(async (value) => {
        this.plugin.settings.opencliPath = value || "opencli";
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/opencli.ts
var import_child_process = require("child_process");
var import_util = require("util");
var import_fs = require("fs");
var import_os = require("os");
var import_path = require("path");
var execAsync = (0, import_util.promisify)(import_child_process.exec);
var EXTRA_PATH = "/Users/yangfan/.npm-global/bin:/usr/local/bin:/opt/homebrew/bin";
var EXEC_ENV = Object.assign({}, process.env, {
  PATH: `${process.env.PATH}:${EXTRA_PATH}`,
  HOME: "/Users/yangfan"
});
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
var EXTRACT_USERID_JS = `document.querySelector('#app').__vue_app__.config.globalProperties['$pinia'].state.value.user.userInfo.userId`;
var EXTRACT_COUNT_JS = `var p=document.querySelector('#app').__vue_app__.config.globalProperties['$pinia'];var t=p.state.value.user.notes['1'];Object.keys(t).length`;
var EXTRACT_FAVORITES_JS = `var p=document.querySelector('#app').__vue_app__.config.globalProperties['$pinia'];var t=p.state.value.user.notes['1'];var r=[];for(var k in t){var n=t[k];if(n&&n.noteCard){var nc=n.noteCard;r.push({id:nc.noteId||n.id,title:nc.displayTitle||'',type:nc.type||'normal',coverUrl:nc.cover?nc.cover.urlDefault:'',nickname:nc.user?nc.user.nickname:'',xsecToken:nc.xsecToken||n.xsecToken||''});}}JSON.stringify(r)`;
var EXTRACT_FAVORITES_IDS_JS = `var p=document.querySelector('#app').__vue_app__.config.globalProperties['$pinia'];var t=p.state.value.user.notes['1'];var r=[];for(var k in t){var n=t[k];if(n&&n.noteCard){r.push(n.noteCard.noteId||n.id)}}JSON.stringify(r)`;
function writeTempJs(content) {
  const file = (0, import_path.join)((0, import_os.tmpdir)(), `xhs_eval_${Date.now()}.js`);
  (0, import_fs.writeFileSync)(file, content, "utf-8");
  return file;
}
var OpenCLIClient = class {
  constructor(opencliPath, scrollDelay) {
    this.session = "xhs";
    this.opencliPath = opencliPath;
    this.scrollDelay = scrollDelay;
  }
  async exec(cmd, opts) {
    return execAsync(cmd, { ...opts, env: EXEC_ENV });
  }
  async evalJs(jsCode) {
    const tmpFile = writeTempJs(jsCode);
    try {
      const cmd = `${this.opencliPath} browser ${this.session} eval "$(cat '${tmpFile}')"`;
      const { stdout } = await this.exec(cmd);
      return stdout.trim();
    } finally {
      try {
        (0, import_fs.unlinkSync)(tmpFile);
      } catch (e) {
      }
    }
  }
  async checkAvailable() {
    try {
      const { stdout, stderr } = await this.exec(`${this.opencliPath} doctor 2>&1`, {
        timeout: 15e3
      });
      const output = stdout + "\n" + stderr;
      if (output.includes("[OK] Extension: connected")) {
        return { available: true };
      }
      return { available: false, error: `opencli \u8FDE\u63A5\u5F02\u5E38:
${output.substring(0, 500)}` };
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      return { available: false, error: `\u65E0\u6CD5\u8FD0\u884C opencli:
${msg.substring(0, 500)}` };
    }
  }
  async getCurrentUserId() {
    const result = await this.evalJs(EXTRACT_USERID_JS);
    return result.replace(/"/g, "");
  }
  async waitForPageReady(userId, maxRetries = 2, onProgress) {
    for (let attempt = 0; attempt < maxRetries; attempt++) {
      if (attempt > 0) {
        onProgress == null ? void 0 : onProgress(`\u9875\u9762\u52A0\u8F7D\u5931\u8D25\uFF0C\u7B2C ${attempt + 1} \u6B21\u91CD\u8BD5...`);
        await this.evalJs("location.reload()");
        await sleep(5e3);
      }
      await sleep(4e3);
      for (let check = 0; check < 10; check++) {
        const title = await this.evalJs("document.title");
        if (title && title.includes("\u5C0F\u7EA2\u4E66")) {
          const userIdCheck = await this.evalJs(EXTRACT_USERID_JS).catch(() => "");
          if (userIdCheck && userIdCheck.length > 10) {
            return true;
          }
        }
        await sleep(2e3);
      }
    }
    return false;
  }
  async dismissPopups() {
    for (let i = 0; i < 3; i++) {
      try {
        await this.evalJs(
          "document.querySelectorAll('button').forEach(function(b){if(b.textContent.includes('\u6211\u77E5\u9053\u4E86'))b.click()})"
        );
        await sleep(300);
      } catch (e) {
      }
    }
    try {
      await this.evalJs(
        "document.querySelectorAll('button').forEach(function(b){if(b.textContent.includes('\u7533\u8BC9'))b.parentElement&&b.parentElement.removeChild(b)})"
      );
    } catch (e) {
    }
  }
  async clickFavoritesTab() {
    try {
      await this.evalJs(
        "document.querySelectorAll('span').forEach(function(s){if(s.textContent==='\u6536\u85CF')s.click()})"
      );
      await sleep(2e3);
      const checkUrl = await this.evalJs("window.location.href");
      if (checkUrl.includes("tab=fav")) {
        return true;
      }
      await this.evalJs(
        "document.querySelectorAll('span').forEach(function(s){if(s.textContent==='\u6536\u85CF')s.click()})"
      );
      await sleep(2e3);
      const checkUrl2 = await this.evalJs("window.location.href");
      return checkUrl2.includes("tab=fav");
    } catch (e) {
      return false;
    }
  }
  async getFavorites(userId, mode, stopAtId, onProgress) {
    onProgress == null ? void 0 : onProgress("Opening your profile page...");
    await this.exec(
      `${this.opencliPath} browser ${this.session} open "https://www.xiaohongshu.com/user/profile/${userId}"`
    );
    const ready = await this.waitForPageReady(userId, 2, onProgress);
    if (!ready) {
      throw new Error("\u9875\u9762\u52A0\u8F7D\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5\uFF1A\n1. \u5C0F\u7EA2\u4E66\u662F\u5426\u5DF2\u767B\u5F55\n2. \u7F51\u7EDC\u662F\u5426\u6B63\u5E38\n3. userId \u662F\u5426\u6B63\u786E");
    }
    onProgress == null ? void 0 : onProgress("Dismissing popups...");
    await this.dismissPopups();
    await sleep(500);
    onProgress == null ? void 0 : onProgress("Clicking favorites tab...");
    const tabClicked = await this.clickFavoritesTab();
    if (!tabClicked) {
      const debugInfo = await this.evalJs(
        "var spans=document.querySelectorAll('span');var texts=[];for(var i=0;i<spans.length;i++)texts.push(spans[i].textContent.trim());JSON.stringify(texts.filter(function(t){return t.length>0&&t.length<10}).slice(0,30))"
      ).catch(() => "failed to get debug info");
      throw new Error(`\u672A\u627E\u5230\u6536\u85CF\u6807\u7B7E\u9875\u3002\u9875\u9762\u6587\u672C: ${debugInfo.substring(0, 300)}`);
    }
    onProgress == null ? void 0 : onProgress(mode === "incremental" && stopAtId ? "Scrolling to find new favorites (incremental)..." : "Scrolling to load all favorites...");
    let lastCount = 0;
    let stable = 0;
    const maxIterations = 200;
    for (let i = 0; i < maxIterations; i++) {
      await this.exec(`${this.opencliPath} browser ${this.session} scroll down`);
      await sleep(this.scrollDelay);
      try {
        const countStr = await this.evalJs(EXTRACT_COUNT_JS);
        const count = parseInt(countStr);
        if (isNaN(count)) {
          stable++;
          if (stable >= 5) break;
          continue;
        }
        onProgress == null ? void 0 : onProgress(`Loaded ${count} favorites...`);
        if (stopAtId) {
          const idsStr = await this.evalJs(EXTRACT_FAVORITES_IDS_JS);
          try {
            const currentIds = JSON.parse(idsStr);
            if (currentIds.includes(stopAtId)) {
              onProgress == null ? void 0 : onProgress("Found last known favorite, stopping...");
              break;
            }
          } catch (e) {
          }
        }
        if (count === lastCount) {
          stable++;
          if (stable >= 3) break;
        } else {
          stable = 0;
        }
        lastCount = count;
      } catch (e) {
        stable++;
        if (stable >= 5) break;
      }
    }
    onProgress == null ? void 0 : onProgress("Extracting favorites data...");
    const json = await this.evalJs(EXTRACT_FAVORITES_JS);
    let result;
    try {
      result = JSON.parse(json);
    } catch (e) {
      const match = json.match(/\[.*\]/s);
      if (match) {
        result = JSON.parse(match[0]);
      } else {
        throw new Error("Failed to parse favorites data from opencli. Raw output: " + json.substring(0, 200));
      }
    }
    onProgress == null ? void 0 : onProgress(`Found ${result.length} favorites`);
    return result;
  }
};

// src/importer.ts
var import_obsidian2 = require("obsidian");

// src/parser.ts
function extractTitle(html) {
  const match = html.match(/<title>(.*?)<\/title>/);
  if (match) {
    return match[1].replace(/ - 小红书$/, "").trim();
  }
  return "Untitled";
}
function extractContent(html) {
  const stateMatch = html.match(
    /window\.__INITIAL_STATE__=(.*?)<\/script>/s
  );
  if (stateMatch) {
    try {
      const jsonStr = stateMatch[1].trim().replace(/undefined/g, "null");
      const state = JSON.parse(jsonStr);
      const key = Object.keys(state.note.noteDetailMap)[0];
      if (key && state.note.noteDetailMap[key]) {
        const note = state.note.noteDetailMap[key].note;
        return (note == null ? void 0 : note.desc) || "";
      }
    } catch (e) {
    }
  }
  const descMatch = html.match(
    /<div id="detail-desc" class="desc">([\s\S]*?)<\/div>/
  );
  if (descMatch) {
    return descMatch[1].replace(/<[^>]+>/g, "").trim();
  }
  return "";
}
function extractImages(html) {
  const stateMatch = html.match(
    /window\.__INITIAL_STATE__=(.*?)<\/script>/s
  );
  if (!stateMatch) return [];
  try {
    const jsonStr = stateMatch[1].trim().replace(/undefined/g, "null");
    const state = JSON.parse(jsonStr);
    const key = Object.keys(state.note.noteDetailMap)[0];
    if (key && state.note.noteDetailMap[key]) {
      const imageList = state.note.noteDetailMap[key].note.imageList || [];
      return imageList.map((img) => img.urlDefault || img.url || "").filter(Boolean);
    }
  } catch (e) {
  }
  return [];
}
function extractVideoUrl(html) {
  var _a;
  const stateMatch = html.match(
    /window\.__INITIAL_STATE__=(.*?)<\/script>/s
  );
  if (!stateMatch) return "";
  try {
    const jsonStr = stateMatch[1].trim().replace(/undefined/g, "null");
    const state = JSON.parse(jsonStr);
    const key = Object.keys(state.note.noteDetailMap)[0];
    if (key && state.note.noteDetailMap[key]) {
      const video = state.note.noteDetailMap[key].note.video;
      if (video) {
        return ((_a = video.consumer) == null ? void 0 : _a.originVideoKey) || video.url || "";
      }
    }
  } catch (e) {
  }
  return "";
}
function extractTags(html) {
  const stateMatch = html.match(
    /window\.__INITIAL_STATE__=(.*?)<\/script>/s
  );
  if (!stateMatch) return [];
  try {
    const jsonStr = stateMatch[1].trim().replace(/undefined/g, "null");
    const state = JSON.parse(jsonStr);
    const key = Object.keys(state.note.noteDetailMap)[0];
    if (key && state.note.noteDetailMap[key]) {
      const tagList = state.note.noteDetailMap[key].note.tagList || [];
      return tagList.map((t) => t.name).filter(Boolean);
    }
  } catch (e) {
  }
  return [];
}
function isVideoNote(html) {
  const stateMatch = html.match(
    /window\.__INITIAL_STATE__=(.*?)<\/script>/s
  );
  if (!stateMatch) return false;
  try {
    const jsonStr = stateMatch[1].trim().replace(/undefined/g, "null");
    const state = JSON.parse(jsonStr);
    const key = Object.keys(state.note.noteDetailMap)[0];
    if (key && state.note.noteDetailMap[key]) {
      return state.note.noteDetailMap[key].note.type === "video";
    }
  } catch (e) {
  }
  return false;
}
function extractStats(html) {
  const stateMatch = html.match(
    /window\.__INITIAL_STATE__=(.*?)<\/script>/s
  );
  const defaults = { likes: 0, collects: 0, comments: 0 };
  if (!stateMatch) return defaults;
  try {
    const jsonStr = stateMatch[1].trim().replace(/undefined/g, "null");
    const state = JSON.parse(jsonStr);
    const key = Object.keys(state.note.noteDetailMap)[0];
    if (key && state.note.noteDetailMap[key]) {
      const interactInfo = state.note.noteDetailMap[key].note.interactInfo;
      if (interactInfo) {
        return {
          likes: parseInt(interactInfo.likedCount) || 0,
          collects: parseInt(interactInfo.collectedCount) || 0,
          comments: parseInt(interactInfo.commentCount) || 0
        };
      }
    }
  } catch (e) {
  }
  return defaults;
}
function extractAuthor(html) {
  const stateMatch = html.match(
    /window\.__INITIAL_STATE__=(.*?)<\/script>/s
  );
  if (!stateMatch) return "";
  try {
    const jsonStr = stateMatch[1].trim().replace(/undefined/g, "null");
    const state = JSON.parse(jsonStr);
    const key = Object.keys(state.note.noteDetailMap)[0];
    if (key && state.note.noteDetailMap[key]) {
      const user = state.note.noteDetailMap[key].note.user;
      if (user) {
        return user.nickname || "";
      }
    }
  } catch (e) {
  }
  return "";
}
function parseNoteDetail(html, noteId) {
  const stats = extractStats(html);
  return {
    title: extractTitle(html),
    content: extractContent(html),
    images: extractImages(html),
    videoUrl: extractVideoUrl(html),
    tags: extractTags(html),
    isVideo: isVideoNote(html),
    likes: stats.likes,
    collects: stats.collects,
    comments: stats.comments,
    author: extractAuthor(html)
  };
}
function generateMarkdown(detail, noteId, xsecToken, category) {
  const prefix = detail.isVideo ? "[V] " : "";
  const noteUrl = `https://www.xiaohongshu.com/explore/${noteId}?xsec_token=${xsecToken}`;
  const now = /* @__PURE__ */ new Date();
  const date = now.toISOString().split("T")[0];
  const importTime = now.toISOString();
  const frontmatter = [
    "---",
    `title: "${prefix}${detail.title}"`,
    `source: ${noteUrl}`,
    `date: ${date}`,
    `Imported At: ${importTime}`,
    `category: ${category}`,
    `author: ${detail.author}`,
    `likes: ${detail.likes}`,
    `collects: ${detail.collects}`,
    `comments: ${detail.comments}`,
    "---"
  ].join("\n");
  const parts = [`

# ${prefix}${detail.title}
`];
  if (detail.content) {
    parts.push(`
${detail.content}
`);
  }
  if (detail.tags.length > 0) {
    parts.push(`
${detail.tags.map((t) => `#${t}`).join(" ")}
`);
  }
  if (detail.images.length > 0) {
    for (const img of detail.images) {
      parts.push(`
![Image](${img})`);
    }
  }
  return frontmatter + parts.join("");
}

// src/importer.ts
function sleep2(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
async function getExistingSources(vault, folder) {
  const existing = /* @__PURE__ */ new Set();
  const files = vault.getFiles().filter((f) => f.path.startsWith(folder));
  for (const file of files) {
    try {
      const content = await vault.read(file);
      const match = content.match(/^---\n([\s\S]*?)\n---/);
      if (match) {
        const sourceMatch = match[1].match(/source:\s*.+/);
        if (sourceMatch) {
          const idMatch = sourceMatch[0].match(/(?:explore|discovery\/item)\/([a-zA-Z0-9]+)/);
          if (idMatch) {
            existing.add(idMatch[1]);
          }
        }
      }
    } catch (e) {
    }
  }
  return existing;
}
async function fetchNoteDetail(noteId, xsecToken) {
  try {
    const url = `https://www.xiaohongshu.com/explore/${noteId}?xsec_token=${xsecToken}`;
    const response = await (0, import_obsidian2.requestUrl)({
      url,
      headers: {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8"
      }
    });
    const html = response.text;
    return parseNoteDetail(html, noteId);
  } catch (e) {
    console.error(`Failed to fetch note ${noteId}:`, e);
    return null;
  }
}
async function batchImport(app, notes, category, settings, onProgress) {
  let success = 0;
  let failed = 0;
  let skipped = 0;
  const folder = `${settings.defaultFolder}/${category}`;
  try {
    await app.vault.createFolder(folder);
  } catch (e) {
  }
  const existing = await getExistingSources(app.vault, settings.defaultFolder);
  for (let i = 0; i < notes.length; i++) {
    const note = notes[i];
    if (existing.has(note.id)) {
      skipped++;
      continue;
    }
    onProgress == null ? void 0 : onProgress(i + 1, notes.length, note.title);
    const detail = await fetchNoteDetail(note.id, note.xsecToken);
    if (!detail) {
      failed++;
      continue;
    }
    const md = generateMarkdown(detail, note.id, note.xsecToken, category);
    const fileName = detail.isVideo ? `[V] ${detail.title}` : detail.title;
    const safeFileName = fileName.replace(/[\\/:*?"<>|]/g, "_").substring(0, 200);
    const filePath = `${folder}/${safeFileName}.md`;
    try {
      await app.vault.create(filePath, md);
      success++;
      existing.add(note.id);
    } catch (e) {
      if (e instanceof Error && e.message.includes("already exists")) {
        const uniqueName = `${folder}/${safeFileName} - ${Date.now()}.md`;
        try {
          await app.vault.create(uniqueName, md);
          success++;
          existing.add(note.id);
        } catch (e2) {
          failed++;
        }
      } else {
        failed++;
      }
    }
    await sleep2(settings.requestDelay);
  }
  return { success, failed, skipped };
}

// src/modal.ts
var import_obsidian3 = require("obsidian");
var BatchImportModal = class extends import_obsidian3.Modal {
  constructor(app, notes, existingIds, settings, onConfirm) {
    super(app);
    this.checkedNotes = /* @__PURE__ */ new Set();
    this.listContainerEl = null;
    this.updateSelectedCount = null;
    this.notes = notes;
    this.existingIds = existingIds;
    this.settings = settings;
    this.selectedCategory = settings.categories[0] || "AI";
    this.downloadMedia = settings.downloadMedia;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    const unimported = this.notes.filter((n) => !this.existingIds.has(n.id));
    contentEl.createEl("h2", { text: "\u{1F4D5} \u5C0F\u7EA2\u4E66\u6536\u85CF\u6279\u91CF\u5BFC\u5165" });
    const statsEl = contentEl.createDiv({ cls: "xhs-stats" });
    statsEl.createSpan({
      text: `\u627E\u5230 ${this.notes.length} \u6761\u6536\u85CF\uFF0C\u5176\u4E2D ${this.existingIds.size} \u6761\u5DF2\u5BFC\u5165`
    });
    const unimportedEl = statsEl.createDiv();
    unimportedEl.createSpan({
      text: `\u4EE5\u4E0B ${unimported.length} \u6761\u672A\u5BFC\u5165\uFF1A`,
      cls: "xhs-unimported-count"
    });
    const controlsEl = contentEl.createDiv({ cls: "xhs-controls" });
    new import_obsidian3.Setting(controlsEl).addButton(
      (btn) => btn.setButtonText("\u5168\u9009").onClick(() => {
        unimported.forEach((n) => this.checkedNotes.add(n.id));
        this.refreshList();
      })
    ).addButton(
      (btn) => btn.setButtonText("\u53D6\u6D88\u5168\u9009").onClick(() => {
        this.checkedNotes.clear();
        this.refreshList();
      })
    );
    const categoryEl = controlsEl.createDiv({ cls: "xhs-category-select" });
    categoryEl.createSpan({ text: "\u5206\u7C7B: " });
    const select = categoryEl.createEl("select");
    this.settings.categories.forEach((cat) => {
      const opt = select.createEl("option", { text: cat, value: cat });
      if (cat === this.selectedCategory) opt.selected = true;
    });
    select.addEventListener("change", () => {
      this.selectedCategory = select.value;
    });
    const mediaToggleEl = controlsEl.createDiv({ cls: "xhs-media-toggle" });
    const mediaCheckbox = mediaToggleEl.createEl("input", {
      type: "checkbox"
    });
    mediaCheckbox.checked = this.downloadMedia;
    mediaCheckbox.addEventListener("change", () => {
      this.downloadMedia = mediaCheckbox.checked;
    });
    mediaToggleEl.createSpan({ text: " \u4E0B\u8F7D\u5A92\u4F53 (\u9ED8\u8BA4\u4E0D\u4E0B\u8F7D\uFF0C\u8282\u7701\u7A7A\u95F4)" });
    this.renderList(unimported);
    const footerEl = contentEl.createDiv({ cls: "xhs-footer" });
    const selectedCountEl = footerEl.createSpan({
      cls: "xhs-selected-count",
      text: `\u5DF2\u9009 0 \u6761`
    });
    new import_obsidian3.Setting(footerEl).addButton(
      (btn) => btn.setButtonText("\u5F00\u59CB\u5BFC\u5165").setCta().onClick(() => {
        const selected = unimported.filter(
          (n) => this.checkedNotes.has(n.id)
        );
        if (selected.length === 0) {
          return;
        }
        this.onConfirm(selected, this.selectedCategory, this.downloadMedia);
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("\u53D6\u6D88").onClick(() => {
        this.close();
      })
    );
    this.updateSelectedCount = () => {
      selectedCountEl.setText(`\u5DF2\u9009 ${this.checkedNotes.size} \u6761`);
    };
    this.updateSelectedCount();
  }
  renderList(unimported) {
    if (this.listContainerEl) {
      this.listContainerEl.empty();
    } else {
      this.listContainerEl = this.contentEl.createDiv({
        cls: "xhs-note-list"
      });
    }
    const maxDisplay = 200;
    const displayNotes = unimported.slice(0, maxDisplay);
    for (const note of displayNotes) {
      const row = this.listContainerEl.createDiv({ cls: "xhs-note-row" });
      const checkbox = row.createEl("input", { type: "checkbox" });
      checkbox.checked = this.checkedNotes.has(note.id);
      checkbox.addEventListener("change", () => {
        var _a;
        if (checkbox.checked) {
          this.checkedNotes.add(note.id);
        } else {
          this.checkedNotes.delete(note.id);
        }
        (_a = this.updateSelectedCount) == null ? void 0 : _a.call(this);
      });
      const typeIndicator = note.type === "video" ? "[V] " : "";
      const title = note.title || "(\u65E0\u6807\u9898)";
      row.createSpan({
        text: `${typeIndicator}${title}`,
        cls: "xhs-note-title"
      });
      if (note.nickname) {
        row.createSpan({
          text: ` - ${note.nickname}`,
          cls: "xhs-note-author"
        });
      }
    }
    if (unimported.length > maxDisplay) {
      this.listContainerEl.createDiv({
        cls: "xhs-more-hint",
        text: `... \u8FD8\u6709 ${unimported.length - maxDisplay} \u6761\u672A\u663E\u793A`
      });
    }
  }
  refreshList() {
    var _a;
    const unimported = this.notes.filter((n) => !this.existingIds.has(n.id));
    this.renderList(unimported);
    (_a = this.updateSelectedCount) == null ? void 0 : _a.call(this);
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var PasteJsonModal = class extends import_obsidian4.Modal {
  constructor(app, onConfirm) {
    super(app);
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u7C98\u8D34\u6536\u85CF JSON \u6570\u636E" });
    contentEl.createEl("p", {
      text: "\u5728\u5C0F\u7EA2\u4E66\u6536\u85CF\u9875\u7684\u6D4F\u89C8\u5668\u63A7\u5236\u53F0\u4E2D\u6267\u884C\u4EE5\u4E0B\u4EE3\u7801\uFF0C\u5C06\u7ED3\u679C\u7C98\u8D34\u5230\u4E0B\u65B9\uFF1A"
    });
    const codeEl = contentEl.createEl("pre", { cls: "xhs-code-block" });
    codeEl.setText(
      `var p=document.querySelector('#app').__vue_app__.config.globalProperties.$pinia;var t=p.state.value.user.notes['1'];var r=[];for(var k in t){var n=t[k];if(n&&n.noteCard){var nc=n.noteCard;r.push({id:nc.noteId||n.id,title:nc.displayTitle||'',type:nc.type||'normal',coverUrl:nc.cover?nc.cover.urlDefault:'',nickname:nc.user?nc.user.nickname:'',xsecToken:nc.xsecToken||n.xsecToken||''});}}JSON.stringify(r);`
    );
    const textarea = contentEl.createEl("textarea", {
      cls: "xhs-paste-input",
      attr: {
        placeholder: "\u5728\u6B64\u7C98\u8D34 JSON \u6570\u636E...",
        rows: "10",
        cols: "60"
      }
    });
    new import_obsidian4.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("\u89E3\u6790\u5E76\u5BFC\u5165").setCta().onClick(() => {
        try {
          const json = textarea.value.trim();
          const notes = JSON.parse(json);
          this.onConfirm(notes);
          this.close();
        } catch (e) {
          new import_obsidian4.Notice("JSON \u89E3\u6790\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5\u683C\u5F0F");
        }
      })
    ).addButton(
      (btn) => btn.setButtonText("\u53D6\u6D88").onClick(() => {
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
var XHSBatchImporterPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.cachedFavorites = null;
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("book-open", "XHS Batch Importer", () => {
      this.startImport();
    });
    this.addCommand({
      id: "xhs-batch-import",
      name: "Import from XHS favorites",
      callback: () => {
        this.startImport();
      }
    });
    this.addCommand({
      id: "xhs-paste-import",
      name: "Import from pasted JSON",
      callback: () => {
        this.pasteImport();
      }
    });
    this.addSettingTab(new XHSBatchImporterSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.cachedFavorites = await this.loadCachedFavorites();
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async loadCachedFavorites() {
    try {
      const data = await this.app.vault.adapter.read(
        this.app.vault.adapter.getFullPath() + "/.obsidian/plugins/xhs-batch-importer/cached-favorites.json"
      );
      return JSON.parse(data);
    } catch (e) {
      return null;
    }
  }
  async saveCachedFavorites(favorites) {
    const cache = {
      notes: favorites,
      timestamp: Date.now()
    };
    this.cachedFavorites = cache;
    try {
      const pluginDir = this.app.vault.adapter.getFullPath() + "/.obsidian/plugins/xhs-batch-importer";
      await this.app.vault.adapter.write(
        pluginDir + "/cached-favorites.json",
        JSON.stringify(cache)
      );
    } catch (e) {
    }
  }
  mergeFavorites(newNotes, cachedNotes) {
    const seen = /* @__PURE__ */ new Set();
    const result = [];
    for (const n of newNotes) {
      if (!seen.has(n.id)) {
        seen.add(n.id);
        result.push(n);
      }
    }
    for (const n of cachedNotes) {
      if (!seen.has(n.id)) {
        seen.add(n.id);
        result.push(n);
      }
    }
    return result;
  }
  async startImport() {
    var _a;
    const client = new OpenCLIClient(
      this.settings.opencliPath,
      this.settings.autoScrollDelay
    );
    const result = await client.checkAvailable();
    if (!result.available) {
      new import_obsidian4.Notice(`opencli \u4E0D\u53EF\u7528: ${result.error || "\u672A\u77E5\u9519\u8BEF"}
\u4E5F\u53EF\u4F7F\u7528\u300C\u4ECE JSON \u7C98\u8D34\u300D\u547D\u4EE4\u3002`, 8e3);
      return;
    }
    let userId = this.settings.userId;
    new import_obsidian4.Notice("\u6B63\u5728\u83B7\u53D6\u7528\u6237 ID...");
    try {
      const browserUserId = await client.getCurrentUserId();
      if (browserUserId && browserUserId.length > 5) {
        userId = browserUserId;
        if (userId !== this.settings.userId) {
          this.settings.userId = userId;
          await this.saveSettings();
          new import_obsidian4.Notice(`\u5DF2\u66F4\u65B0\u7528\u6237 ID: ${userId}`);
        }
      } else if (!userId) {
        new import_obsidian4.Notice("\u83B7\u53D6\u7528\u6237 ID \u5931\u8D25\uFF0C\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u624B\u52A8\u586B\u5199\u3002");
        return;
      }
    } catch (e) {
      if (!userId) {
        new import_obsidian4.Notice("\u83B7\u53D6\u7528\u6237 ID \u5931\u8D25\uFF0C\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u624B\u52A8\u586B\u5199\u3002");
        return;
      }
    }
    const mode = this.settings.importMode;
    const cachedNotes = ((_a = this.cachedFavorites) == null ? void 0 : _a.notes) || [];
    const stopAtId = mode === "incremental" && cachedNotes.length > 0 ? cachedNotes[0].id : void 0;
    const modeLabel = mode === "incremental" && cachedNotes.length > 0 ? `\uFF08\u589E\u91CF\u6A21\u5F0F\uFF1A\u4ECE\u4E0A\u6B21\u6700\u65B0\u6536\u85CF\u5F00\u59CB\u8BFB\u53D6\uFF0C\u5DF2\u7F13\u5B58 ${cachedNotes.length} \u6761\uFF09` : "\uFF08\u5B8C\u6574\u6A21\u5F0F\uFF1A\u83B7\u53D6\u6240\u6709\u6536\u85CF\uFF09";
    new import_obsidian4.Notice(`\u6B63\u5728\u52A0\u8F7D\u6536\u85CF\u5217\u8868${modeLabel}\uFF0C\u8BF7\u7B49\u5F85...`);
    let freshNotes;
    try {
      const notice = new import_obsidian4.Notice("\u52A0\u8F7D\u4E2D...", 0);
      freshNotes = await client.getFavorites(userId, mode, stopAtId, (msg) => {
        notice.setMessage(msg);
      });
      notice.hide();
    } catch (e) {
      new import_obsidian4.Notice(`\u83B7\u53D6\u6536\u85CF\u5931\u8D25: ${e.message}`, 1e4);
      return;
    }
    const allFavorites = this.mergeFavorites(freshNotes, cachedNotes);
    await this.saveCachedFavorites(allFavorites);
    const existingIds = await getExistingSources(
      this.app.vault,
      this.settings.defaultFolder
    );
    const importedCount = allFavorites.filter((n) => existingIds.has(n.id)).length;
    const newCount = allFavorites.length - importedCount;
    new import_obsidian4.Notice(`\u5171 ${allFavorites.length} \u6761\u6536\u85CF\uFF0C${importedCount} \u6761\u5DF2\u5BFC\u5165\uFF0C${newCount} \u6761\u672A\u5BFC\u5165`);
    new BatchImportModal(
      this.app,
      allFavorites,
      existingIds,
      this.settings,
      async (selected, category, downloadMedia) => {
        await this.runImport(selected, category, downloadMedia);
      }
    ).open();
  }
  async pasteImport() {
    const modal = new PasteJsonModal(this.app, async (notes) => {
      const existingIds = await getExistingSources(
        this.app.vault,
        this.settings.defaultFolder
      );
      new BatchImportModal(
        this.app,
        notes,
        existingIds,
        this.settings,
        async (selected, category, downloadMedia) => {
          await this.runImport(selected, category, downloadMedia);
        }
      ).open();
    });
    modal.open();
  }
  async runImport(selected, category, downloadMedia) {
    const notice = new import_obsidian4.Notice("\u5F00\u59CB\u5BFC\u5165...", 0);
    const settings = { ...this.settings, downloadMedia };
    const result = await batchImport(
      this.app,
      selected,
      category,
      settings,
      (current, total, title) => {
        notice.setMessage(
          `\u5BFC\u5165\u4E2D (${current}/${total}): ${title.substring(0, 30)}...`
        );
      }
    );
    notice.hide();
    new import_obsidian4.Notice(
      `\u5BFC\u5165\u5B8C\u6210\uFF01\u6210\u529F ${result.success} \u6761\uFF0C\u5931\u8D25 ${result.failed} \u6761\uFF0C\u8DF3\u8FC7 ${result.skipped} \u6761`
    );
  }
};
